### ISSUE TITLE
INFO fileds char issue

### ISSUE THREAD

**Issue by sb43** [cancerit/vcf_flag_modifier#2]
colon[:] in flag modified vcf file INFO field converts to %3A.
 e.g., Info line in input vcf file:
FF017;LEN=1;PC=D;RE=15946085;REP=1;RS=15946083;S1=260;S2=1252.05;VT=Del;VD=MYCN|CCDS1687.1|r.1693delC|c.1382delC|p.A461fs*29|protein_coding:exon:CDS:deletion:frameshift_variant|SO:0000010:SO:0000147:SO:0000316:SO:0000159:SO:0001589;VC=frameshift;VW=MYCN|CCDS1687.1|r.1693delC|c.1382delC|p.A461fs*29|protein_coding:exon:CDS:deletion:frameshift_variant|SO:0000010:SO:0000147:SO:0000316:SO:0000159:SO:0001589
 
Info line in flag modified output vcf file:

FF017;LEN=1;PC=D;RE=15946085;REP=1;RS=15946083;S1=260;S2=1252.05;VC=frameshift;VD=MYCN|CCDS1687.1|r.1693delC|c.1382delC|p.A461fs*29|protein_coding%3Aexon%3ACDS%3Adeletion%3Aframeshift_variant|SO%3A0000010%3ASO%3A0000147%3ASO%3A0000316%3ASO%3A0000159%3ASO%3A0001589;VT=Del;VW=MYCN|CCDS1687.1|r.1693delC|c.1382delC|p.A461fs*29|protein_coding%3Aexon%3ACDS%3Adeletion%3Aframeshift_variant|SO%3A0000010%3ASO%3A0000147%3ASO%3A0000316%3ASO%3A0000159%3ASO%3A0001589

**Comment by kathryn-beal** [comment]
This is due to the vcfpy library escaping particular reserved characters, including the colon when writing the records. According to the VCF specifications, colons are not excluded from the INFO field string values. I have raised an [issue](https://github.com/bihealth/vcfpy/issues/136)

**Comment by kathryn-beal** [comment]
The vcfpy library has been updated and a new version of vcf_flag_modifier has been released.
